### ISSUE TITLE
Remove Racist Comments in the code. 

### ISSUE THREAD

**Issue by 7RingsOfSaturn** [mfd-engine-team/robloxlabs.com#5]
This issue is present in files: 
* https://github.com/mfd-engine-team/robloxlabs.com/blob/Roblox.SiteTest4/Roblox/Controllers/SimulPong.TeamCity/Login.ts
* https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Roblox/Controllers/Roblox.PrivateMessages/v1/announcements.ts
* https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Manifest/persistence/0/stores/sucksss/scopes/_/RECORD.json

Reference to such slurs should not be on your github page.

**Comment by rbx-nsg** [comment]
OK

**Comment by Yakov5776** [comment]
You should make a PR

**Comment by rbx-nsg** [comment]
https://github.com/mfd-engine-team/robloxlabs.com/commit/1862a5363e5c733fc9238cdcce72c0230b48568b
https://github.com/mfd-engine-team/robloxlabs.com/commit/bf4608bd840e971a188f158aa11b55ea7ec51dd9

**Comment by 7RingsOfSaturn** [comment]
It seems the issue has been resolved in two files so far, but there is still one remaining. 

fixed: 1862a5363e5c733fc9238cdcce72c0230b48568b
fixed: bf4608bd840e971a188f158aa11b55ea7ec51dd9

persisting issue: https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Manifest/persistence/0/stores/sucksss/scopes/_/RECORD.json

**Comment by rbx-nsg** [comment]
https://github.com/mfd-engine-team/robloxlabs.com/commit/f23c239cec7d0eda16c981413a53f8a16159c261

**Comment by rbx-nsg** [comment]
In that case, help with the DataBase pls

**Comment by 7RingsOfSaturn** [comment]
Issue was not resolved for file: https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Manifest/persistence/0/stores/sucksss/scopes/_/RECORD.json

**Comment by rbx-nsg** [comment]
Yeah because you're looking at a direct commit

**Comment by Yakov5776** [comment]
lol he's not on the main branch

**Comment by 7RingsOfSaturn** [comment]
Okay thanks for resolving these issues. Just make sure to push the profanity removing contributions to the main branch. 

👍

**Comment by rbx-nsg** [comment]
But I did

**Comment by Yakov5776** [comment]
he joined 26 days ago

**Comment by rbx-nsg** [comment]
Actually 24 days ago
