### ISSUE TITLE
Remove Profanity 

### ISSUE THREAD

**Issue by 7RingsOfSaturn** [mfd-engine-team/robloxlabs.com#6]
This is a similar issue to my previous issue which was regarding the usage of slurs within the codebase. (https://github.com/mfd-engine-team/robloxlabs.com/issues/5)

There are several files within the codebase that use inappropriate language that are not specifically racial slurs. Please fix.

* https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Roblox/Controllers/Roblox.Api/universes/get-info.ts
* https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/Roblox/Helpers/WebHelpers/Roblox.Sessions/Roblox.Sessions.CreateOrGetXsrfSession.ts
* https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/StaticPages/Roblox.StaticCDN/rbx/1.rbxlx

**Comment by BrentDaMage** [comment]
Who cares?

**Comment by Yakov5776** [comment]
Just make a PR!

**Comment by rbx-nsg** [comment]
https://github.com/7RingsOfSaturn/Pornhub-Ad-Scraper

**Comment by Yakov5776** [comment]
lol

**Comment by rbx-nsg** [comment]
https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/StaticPages/Roblox.StaticCDN/rbx/1.rbxlx where's the profanity in this?

**Comment by 7RingsOfSaturn** [comment]
> 
> 
> https://github.com/mfd-engine-team/robloxlabs.com/blob/bcad8b177bcc304701dbad3ec5c7df4676960b43/StaticPages/Roblox.StaticCDN/rbx/1.rbxlx where's the profanity in this?

Line 269.

**Comment by ohoshk** [comment]
its funny

**Comment by rbx-nsg** [comment]
But why do you care so much? Do you have children regularly browsing github?

**Comment by 7RingsOfSaturn** [comment]
I just want things, such as repos related to ROBLOX which is a kids game, to not have profanity in them. Please understand.

**Comment by rbx-nsg** [comment]
ROBLOX is not just a kids game, and also this a test site, so shhh

**Comment by XlXi** [comment]
7rings, why the fuck do you care

**Comment by 7RingsOfSaturn** [comment]
> 
> 
> 7rings, why the fuck do you care

could that be xlxi from 3 years ago who would post retarded things in group chats with nicktimestwo

**Comment by BrentDaMage** [comment]
This is remaking web backend. Why on earth would any kid ever even come across this, let alone dig around enough to find the profanity you reported?

**Comment by XlXi** [comment]
7rings, you're literally the retard going to a repo to report profane content, gtfo

**Comment by 7RingsOfSaturn** [comment]
Please stop being mean I am just trying to help.

**Comment by rbx-nsg** [comment]
"Help"

**Comment by 7RingsOfSaturn** [comment]
I will make a Pull request since you guys seem busy.

**Comment by ohoshk** [comment]
lol

**Comment by ohoshk** [comment]
repoistory

**Comment by Yakov5776** [comment]
lol

**Comment by 7RingsOfSaturn** [comment]
> 
> 
> 7rings, you're literally the retard going to a repo to report profane content, gtfo

https://github.com/mfd-engine-team/robloxlabs.com/blob/Roblox.SiteTest4/CODE_OF_CONDUCT.md

**Comment by XlXi** [comment]
7rings, thats pretty funny how you deleted your comment calling me a retard so it looks like im the bad one here

**Comment by XlXi** [comment]
you're a literal fucking nolife troglodyte trying to make me look like i'm the one in the wrong here, when you're literally scraping a repo in an attempt to find any swear word possible, please, for the love of god, take your ass off of github and go do something productive

**Comment by rbx-nsg** [comment]
@7RingsOfSaturn where's the pull request?

**Comment by 7RingsOfSaturn** [comment]
There is no need to make a PR. It appears someone has pushed fixes. 

Anyway, I hope you can respect your own CODE_OF_CONDUCT.md that you guys have. It looks bad if you do not.

**Comment by Yakov5776** [comment]
### test

_vcfdvfdvdf_
test **test**
![FinobePlayer_jM7h4lkZTV](https://user-images.githubusercontent.com/28637006/111088595-4ccd1380-84fe-11eb-9f07-103953363510.png)

**Comment by ohoshk** [comment]
you should as well

**Comment by ohoshk** [comment]
### **_``_**__

**Comment by ohoshk** [comment]
what

**Comment by 7RingsOfSaturn** [comment]
?

**Comment by CMD-X** [comment]
remove profanity!
