### ISSUE TITLE
Program crashes when attempting to load website using HTTPS

### ISSUE THREAD

**Issue by reknohT** [mfd-engine-team/robloxlabs.com#86]
**Describe the bug**
When trying to load any webpage hosted by the server using HTTPS, the program will crash with the error "Name: TypeError, Reason: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined, Stack Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined."

**To Reproduce**
1. Start web server using the command "npm start"
2. Try to load any hosted web page using HTTPS

**Screenshot**
![image](https://user-images.githubusercontent.com/55928577/111852880-b8d8be80-88e6-11eb-8174-bd1402b0e3ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox
 - Version 86.0.1

**Full stack trace**
`[DFLog::Tasks] Name: TypeError, Reason: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined, Stack Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:443:10)
    at Object.writeFile (fs.js:1446:6)
    at Object.appendFile (fs.js:1493:6)
    at Server.E.logLine (C:\buildagent\work\0800fc577294c34f\node_modules\sslkeylog\index.js:14:24)
    at Server.emit (events.js:315:20)
    at Server.emit (C:\buildagent\work\0800fc577294c34f\node_modules\spdy\lib\spdy\server.js:236:40)
    at TLSSocket.onSocketKeylog (_tls_wrap.js:1047:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSWrap.onkeylog (_tls_wrap.js:385:22)`

**Comment by rbx-nsg** [comment]
That is for your sslkeylogfile, just file sslkeylog and npm uninstall it and unref all of it, this was for debugging ssl requests

**Comment by reknohT** [comment]
> 
> 
> That is for your sslkeylogfile, just file sslkeylog and npm uninstall it and unref all of it, this was for debugging ssl requests

Problem solved, thank you.
